prometheus:
  prometheusSpec:
    storageSpec:
      emptyDir:
        medium: ""
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:083127296598:certificate/65d620e4-5b2f-410b-8c85-e4e37063aa51"
      alb.ingress.kubernetes.io/waf-acl-arn: "arn:aws:wafv2:eu-west-1:083127296598:regional/webacl/rhorizon-nonprod-ingress-waf/46965318-47dd-4429-8874-4e506a71deb9"
    hosts:
      - "grafana.nonprod.rhorizon.xyz"
    path: /

  persistence:
    enabled: false
    storageClassName: gp3-encrypted
    size: 10Gi

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
