apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rhorizon
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "rhorizon_dev"
  DB_USER: "dbadmin"
  S3_BUCKET_NAME: "rhorizon-local-assets"
  AWS_REGION: "eu-west-1"
  S3_ENDPOINT_URL: "http://localstack:4566"
  AWS_ACCESS_KEY_ID: "mock"
  AWS_SECRET_ACCESS_KEY: "mock"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: rhorizon
type: Opaque
data:
  DB_PASSWORD: "Ukhab3Jpb25EZXZQYXNzMjAyNiE=" # Base64 for RHZorionDevPass2026!
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhorizon-backend-sa
  namespace: rhorizon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhorizon-backend
  namespace: rhorizon
  labels:
    app: rhorizon-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhorizon-backend
  template:
    metadata:
      labels:
        app: rhorizon-backend
    spec:
      serviceAccountName: rhorizon-backend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: backend
        image: rhorizon-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /api/liveness
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: rhorizon
  labels:
    app: rhorizon-backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: rhorizon-backend
