apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhorizon-localstack
  namespace: rhorizon
  labels:
    app: rhorizon-localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhorizon-localstack
  template:
    metadata:
      labels:
        app: rhorizon-localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.8.0
        env:
        - name: SERVICES
          value: s3
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        ports:
        - containerPort: 4566
          name: edge
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: rhorizon
spec:
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
    name: edge
  selector:
    app: rhorizon-localstack
