apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-frontend
  namespace: rhorizon
spec:
  podSelector:
    matchLabels:
      app: rhorizon-frontend
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: rhorizon
spec:
  podSelector:
    matchLabels:
      app: rhorizon-backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: rhorizon-frontend
    ports:
    - protocol: TCP
      port: 5000
