graph TB
  subgraph AWS_Org ["AWS Organization (Landing Zone)"]
    direction TB

    subgraph OU_Shared ["OU: Infrastructure / Shared Services"]
      acc_shared["Account: Shared Services (116101833976)"]
      acc_shared --> ecr["Amazon ECR (Images Docker)"]
      acc_shared --> route53["Route53 (Zone Parente rhorizon.xyz)"]
      acc_shared --> cicd_iam["IAM OIDC (GitHub Actions Runners)"]
      acc_shared --> central_s3["S3 (Logs, Backups, Assets)"]
      acc_shared --> kms["KMS (Chiffrement Centralisé)"]
    end

    subgraph OU_Workloads ["OU: Workloads"]
      acc_nonprod["Account: Non-Prod (083127296598)"]
      acc_prod["Account: Prod (593402827099)"]

      subgraph VPC_NonProd ["VPC Non-Prod"]
        eks_np["EKS Cluster (App & Monitor)"]
        rds_np["RDS PostgreSQL"]
        bastion_np["SSM Bastion"]
        waf_np["WAF & ALB Ingress"]
      end

      subgraph VPC_Prod ["VPC Prod"]
        eks_p["EKS Cluster (App & Monitor)"]
        rds_p["RDS PostgreSQL"]
        bastion_p["SSM Bastion"]
        waf_p["WAF & ALB Ingress"]
      end

      acc_nonprod --> VPC_NonProd
      acc_prod --> VPC_Prod
    end

    %% Relations Cross-Account
    cicd_iam -.->|"AssumeRole (EKS Access Entries)"| eks_np
    cicd_iam -.->|"AssumeRole (EKS Access Entries)"| eks_p
    ecr -.->|"Pull Images"| eks_np
    ecr -.->|"Pull Images"| eks_p
    route53 -.->|"Délégation DNS NS"| waf_np
    route53 -.->|"Délégation DNS NS"| waf_p
    central_s3 -.->|"Centralized Logs & Assets"| eks_np
    central_s3 -.->|"Centralized Logs & Assets"| eks_p
  end

  classDef account fill:#e1f5fe,stroke:#03a9f4,stroke-width:2px,color:#000
  classDef ou fill:#fafafa,stroke:#9e9e9e,stroke-width:2px,stroke-dasharray: 5 5
  classDef service fill:#fff3e0,stroke:#ff9800,stroke-width:1px

  class acc_shared,acc_nonprod,acc_prod account
  class OU_Shared,OU_Workloads ou
  class ecr,route53,cicd_iam,central_s3,kms,eks_np,rds_np,bastion_np,waf_np,eks_p,rds_p,bastion_p,waf_p service
