stages:
  - validate
  - plan
  - scan
  - deploy

default:
  image: hashicorp/terraform:1.6.0
  before_script:
    - terraform --version

tf_validate:
  stage: validate
  script:
    - cd live/nonprod
    - terraform init -backend=false
    - terraform validate

tf_plan:
  stage: plan
  script:
    - cd live/nonprod
    - terraform init
    - terraform plan -out=tfplan

infra_security_scan:
  stage: scan
  image: 
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  before_script: []
  script:
    - checkov -d live/nonprod/ --framework terraform --soft-fail

tf_apply:
  stage: deploy
  script:
    - cd live/nonprod
    - terraform init
    - terraform apply -auto-approve tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
