name: Security - Signed Commits Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  check-signatures:
    name: Verify Commit Signatures
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Signatures
        uses: 1Password/check-signed-commits-action@v1
