name: Infra Non-Prod Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: Terraform Format Check
        run: |
          cd live/nonprod
          terraform fmt -check

      - name: Terraform Validate
        run: |
          cd live/nonprod
          terraform init -backend=false
          terraform validate

  plan:
    name: Terraform Plan
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116101833976:role/shared-gitlab-ci-role
          aws-region: eu-west-1

      - name: Terraform Init & Plan
        run: |
          cd live/nonprod
          terraform init
          terraform plan -out=tfplan

  scan:
    name: DevSecOps Scan (Checkov)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: live/nonprod/
          framework: terraform
          soft_fail: true

  apply:
    name: Terraform Apply
    needs: [plan, scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116101833976:role/shared-gitlab-ci-role
          aws-region: eu-west-1

      - name: Terraform Init & Apply
        run: |
          cd live/nonprod
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
